#  Copyright (c) 2025 Timofei Kirsanov

from PyQt6 import QtCore, QtGui, QtWidgets

from client import translate


class LoginActivity(object):
    def setupUi(self, centralwidget):
        centralwidget.setObjectName("centralwidget")
        centralwidget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grid = QtWidgets.QGridLayout()
        self.grid.setObjectName("grid")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.grid.addItem(spacerItem, 2, 2, 1, 1)
        self.passwordBox = QtWidgets.QLineEdit(parent=centralwidget)
        self.passwordBox.setInputMask("")
        self.passwordBox.setText("")
        self.passwordBox.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordBox.setObjectName("passwordBox")
        self.grid.addWidget(self.passwordBox, 7, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.grid.addItem(spacerItem1, 1, 3, 1, 1)
        self.loginButton = QtWidgets.QPushButton(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.grid.addWidget(self.loginButton, 8, 1, 1, 2)
        self.registerButton = QtWidgets.QPushButton(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        self.registerButton.setFont(font)
        self.registerButton.setObjectName("registerButton")
        self.grid.addWidget(self.registerButton, 9, 1, 1, 2)
        self.loginText = QtWidgets.QLabel(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.loginText.setFont(font)
        self.loginText.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.loginText.setObjectName("loginText")
        self.grid.addWidget(self.loginText, 6, 1, 1, 1)
        self.loginBox = QtWidgets.QLineEdit(parent=centralwidget)
        self.loginBox.setInputMask("")
        self.loginBox.setObjectName("loginBox")
        self.grid.addWidget(self.loginBox, 6, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.grid.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.grid.addItem(spacerItem3, 1, 0, 1, 1)
        self.passwordText = QtWidgets.QLabel(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.passwordText.setFont(font)
        self.passwordText.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.passwordText.setObjectName("passwordText")
        self.grid.addWidget(self.passwordText, 7, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.grid.addItem(spacerItem4, 10, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.grid.addItem(spacerItem5, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.grid.addWidget(self.label, 1, 1, 1, 2)
        self.verticalLayout.addLayout(self.grid)

        self.retranslateUi(centralwidget)
        QtCore.QMetaObject.connectSlotsByName(centralwidget)

    def retranslateUi(self, centralwidget):
        _translate = QtCore.QCoreApplication.translate
        centralwidget.setWindowTitle(_translate("centralwidget", translate.get("app.name")))
        self.loginButton.setText(_translate("centralwidget", translate.get("auth.button.login")))
        self.registerButton.setText(_translate("centralwidget", translate.get("auth.button.registration")))
        self.loginText.setText(_translate("centralwidget", translate.get("auth.text.login")))
        self.passwordText.setText(_translate("centralwidget", translate.get("auth.text.registration")))
        self.label.setText(_translate("centralwidget", translate.get("app.name")))
