#  Copyright (c) 2025 Timofei Kirsanov

from PyQt6 import QtCore, QtGui, QtWidgets

from client import translate


class MainActivity(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.searchButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.searchButton.setObjectName("searchButton")
        self.gridLayout.addWidget(self.searchButton, 0, 2, 1, 1)
        self.chatInfo = QtWidgets.QWidget(parent=self.centralwidget)
        self.chatInfo.setObjectName("chatInfo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.chatInfo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chatName = QtWidgets.QLabel(parent=self.chatInfo)
        self.chatName.setObjectName("chatName")
        self.horizontalLayout.addWidget(self.chatName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.videoCallButton = QtWidgets.QToolButton(parent=self.chatInfo)
        self.videoCallButton.setObjectName("videoCallButton")
        self.horizontalLayout.addWidget(self.videoCallButton)
        self.callButton = QtWidgets.QToolButton(parent=self.chatInfo)
        self.callButton.setObjectName("callButton")
        self.horizontalLayout.addWidget(self.callButton)
        self.editButton = QtWidgets.QToolButton(parent=self.chatInfo)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.gridLayout.addWidget(self.chatInfo, 0, 5, 1, 3)
        self.chat = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.chat.setWidgetResizable(True)
        self.chat.setObjectName("chat")
        self.messages_container = QtWidgets.QWidget()
        self.messages_container.setGeometry(QtCore.QRect(0, 0, 609, 502))
        self.messages_container.setObjectName("messages_container")
        self.messages_layout = QtWidgets.QVBoxLayout(self.messages_container)
        self.messages_layout.setObjectName("messages_layout")
        self.chat.setWidget(self.messages_container)
        self.gridLayout.addWidget(self.chat, 1, 5, 4, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uploadButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.uploadButton.setObjectName("uploadButton")
        self.horizontalLayout_2.addWidget(self.uploadButton)
        self.sendButton = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(10)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_2.addWidget(self.sendButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 6, 1, 1)
        self.search = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search.sizePolicy().hasHeightForWidth())
        self.search.setSizePolicy(sizePolicy)
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 0, 0, 1, 1)
        self.message = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.message.setObjectName("message")
        self.gridLayout.addWidget(self.message, 6, 5, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.settings = QtWidgets.QToolButton(parent=self.centralwidget)
        self.settings.setObjectName("settings")
        self.horizontalLayout_4.addWidget(self.settings)
        self.createChatButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.createChatButton.setObjectName("createChatButton")
        self.horizontalLayout_4.addWidget(self.createChatButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 0, 1, 3)
        self.chats = QtWidgets.QListWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chats.sizePolicy().hasHeightForWidth())
        self.chats.setSizePolicy(sizePolicy)
        self.chats.setObjectName("chats")
        self.gridLayout.addWidget(self.chats, 1, 0, 4, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", translate.get("app.name")))
        self.searchButton.setText(_translate("MainWindow", "🔍"))
        self.chatName.setText(_translate("MainWindow", translate.get("chat.name")))
        self.videoCallButton.setText(_translate("MainWindow", "🎥"))
        self.callButton.setText(_translate("MainWindow", "📞"))
        self.editButton.setText(_translate("MainWindow", "🖊️"))
        self.uploadButton.setText(_translate("MainWindow", "📎"))
        self.sendButton.setText(_translate("MainWindow", translate.get("chat.send")))
        self.settings.setText(_translate("MainWindow", "⚙️"))
        self.createChatButton.setText(_translate("MainWindow", "➕"))
