#  Copyright (c) 2025 Timofei Kirsanov

from PyQt6 import QtCore, QtGui, QtWidgets

from client import translate


class RegistrationActivity(object):
    def setupUi(self, centralwidget):
        centralwidget.setObjectName("centralwidget")
        centralwidget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grid = QtWidgets.QGridLayout()
        self.grid.setObjectName("grid")
        self.passwordBox = QtWidgets.QLineEdit(parent=centralwidget)
        self.passwordBox.setObjectName("passwordBox")
        self.grid.addWidget(self.passwordBox, 5, 2, 1, 1)
        self.nameText = QtWidgets.QLabel(parent=centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameText.setFont(font)
        self.nameText.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.nameText.setObjectName("nameText")
        self.grid.addWidget(self.nameText, 10, 1, 1, 1)
        self.registerButton = QtWidgets.QPushButton(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        self.registerButton.setFont(font)
        self.registerButton.setObjectName("registerButton")
        self.grid.addWidget(self.registerButton, 11, 1, 1, 2)
        self.nameBox = QtWidgets.QLineEdit(parent=centralwidget)
        self.nameBox.setObjectName("nameBox")
        self.grid.addWidget(self.nameBox, 10, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.grid.addItem(spacerItem, 12, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.grid.addItem(spacerItem1, 3, 2, 1, 1)
        self.retryBox = QtWidgets.QLineEdit(parent=centralwidget)
        self.retryBox.setInputMask("")
        self.retryBox.setText("")
        self.retryBox.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.retryBox.setObjectName("retryBox")
        self.grid.addWidget(self.retryBox, 9, 2, 1, 1)
        self.loginBox = QtWidgets.QLineEdit(parent=centralwidget)
        self.loginBox.setInputMask("")
        self.loginBox.setObjectName("loginBox")
        self.grid.addWidget(self.loginBox, 4, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.grid.addItem(spacerItem2, 0, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.grid.addItem(spacerItem3, 1, 3, 11, 1)
        self.loginText = QtWidgets.QLabel(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.loginText.setFont(font)
        self.loginText.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.loginText.setObjectName("loginText")
        self.grid.addWidget(self.loginText, 4, 1, 1, 1)
        self.passwordText = QtWidgets.QLabel(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.passwordText.setFont(font)
        self.passwordText.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.passwordText.setObjectName("passwordText")
        self.grid.addWidget(self.passwordText, 5, 1, 1, 1)
        self.retryText = QtWidgets.QLabel(parent=centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.retryText.setFont(font)
        self.retryText.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.retryText.setObjectName("retryText")
        self.grid.addWidget(self.retryText, 9, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.grid.addItem(spacerItem4, 1, 0, 11, 1)
        self.verticalLayout.addLayout(self.grid)

        self.retranslateUi(centralwidget)
        QtCore.QMetaObject.connectSlotsByName(centralwidget)

    def retranslateUi(self, centralwidget):
        _translate = QtCore.QCoreApplication.translate
        centralwidget.setWindowTitle(_translate("centralwidget", translate.get("app.name")))
        self.nameText.setText(_translate("centralwidget", "имя:"))
        self.registerButton.setText(_translate("centralwidget", "Регистрация"))
        self.loginText.setText(_translate("centralwidget", "логин:"))
        self.passwordText.setText(_translate("centralwidget", "пароль:"))
        self.retryText.setText(_translate("centralwidget", "повторите:"))
