#  Copyright (c) 2025 Timofei Kirsanov

from PyQt6 import QtCore, QtGui, QtWidgets

from client import translate


class SettingsActivity(object):
    def setupUi(self, centralwidget):
        centralwidget.setObjectName("centralwidget")
        centralwidget.resize(407, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.saveButton = QtWidgets.QPushButton(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setBold(True)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 3, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formatLabel = QtWidgets.QLabel(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        self.formatLabel.setFont(font)
        self.formatLabel.setObjectName("formatLabel")
        self.verticalLayout_4.addWidget(self.formatLabel)
        self.format1 = QtWidgets.QRadioButton(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        self.format1.setFont(font)
        self.format1.setObjectName("format1")
        self.formatGroup = QtWidgets.QButtonGroup(centralwidget)
        self.formatGroup.setObjectName("formatGroup")
        self.formatGroup.addButton(self.format1)
        self.verticalLayout_4.addWidget(self.format1)
        self.format2 = QtWidgets.QRadioButton(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        self.format2.setFont(font)
        self.format2.setObjectName("format2")
        self.formatGroup.addButton(self.format2)
        self.verticalLayout_4.addWidget(self.format2)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.langLabel = QtWidgets.QLabel(parent=centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        self.langLabel.setFont(font)
        self.langLabel.setObjectName("langLabel")
        self.verticalLayout_2.addWidget(self.langLabel)
        self.lang = QtWidgets.QComboBox(parent=centralwidget)
        self.lang.setObjectName("lang")
        self.lang.addItem("")
        self.verticalLayout_2.addWidget(self.lang)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.themeLabel = QtWidgets.QLabel(parent=centralwidget)
        self.themeLabel.setObjectName("themeLabel")
        self.verticalLayout_5.addWidget(self.themeLabel)
        self.theme = QtWidgets.QComboBox(parent=centralwidget)
        self.theme.setObjectName("theme")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.verticalLayout_5.addWidget(self.theme)
        self.gridLayout.addLayout(self.verticalLayout_5, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(centralwidget)
        QtCore.QMetaObject.connectSlotsByName(centralwidget)

    def retranslateUi(self, centralwidget):
        _translate = QtCore.QCoreApplication.translate
        centralwidget.setWindowTitle(_translate("centralwidget", translate.get("settings")))
        self.saveButton.setText(_translate("centralwidget", translate.get("settings.save")))
        self.formatLabel.setText(_translate("centralwidget", translate.get("settings.time.format")))
        self.format1.setText(_translate("centralwidget", "%H:%M"))
        self.format2.setText(_translate("centralwidget", "%H:%M:%S"))
        self.langLabel.setText(_translate("centralwidget", translate.get("settings.language")))
        self.lang.setItemText(0, _translate("centralwidget", "ru_RU"))
        self.themeLabel.setText(_translate("centralwidget", translate.get("settings.theme")))
        self.theme.setItemText(0, _translate("centralwidget", translate.get("settings.theme.system")))
        self.theme.setItemText(1, _translate("centralwidget", translate.get("settings.theme.light")))
        self.theme.setItemText(2, _translate("centralwidget", translate.get("settings.theme.dark")))
